# Generated by Django 6.0.3 on 2026-04-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
