# Generated by Django 6.0.4 on 2026-04-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0007_alter_semester_department_alter_subject_semester_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
