# Generated by Django 6.0.3 on 2026-04-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0009_platformreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('notes_pdf', 'Notes (PDF)'), ('notes_ppt', 'Notes (PPT)'), ('syllabus', 'Syllabus'), ('qp', 'Question Paper')], default='notes_pdf', max_length=20),
        ),
    ]
