# Generated by Django 6.0.4 on 2026-04-14 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSutraapp', '0010_alter_resource_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'mp4', 'webm', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('notes_pdf', 'Notes (PDF)'), ('notes_ppt', 'Notes (PPT)'), ('syllabus', 'Syllabus'), ('qp', 'Question Paper'), ('video', 'Video Lecture')], default='notes_pdf', max_length=20),
        ),
    ]
